name:                fgln
version:             0.1.0.0
github:              "autonomousorganization/fgln"
license:             BSD3

extra-source-files:
- README.md
- CHANGELOG.md

description: Lightning plugin that loads channels into graph object and provides functionality to search channel graph and manage node.

default-extensions: 
- OverloadedStrings
- LambdaCase
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- clplug
- fgl
- containers
- aeson
- lens
- lens-aeson
- text 
- mtl
- format-numbers
- fmt 
- json-rpc
- monomer
- beam-core
- beam-sqlite
- beam-migrate
- sqlite-simple
- text-show
- data-default

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded

library:
  source-dirs: src

executables:
  fgln:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fgln

tests:
  routes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fgln
